version: '3'

services:
  jekyll:
    image: bretfisher/jekyll-serve
    command: [ "bundle", "exec", "jekyll", "serve", "--watch", "-l", "-H", "0.0.0.0", "-P", "4000" ]
    ports:
        - '4000:4000'
        - '35729:35729'
    volumes:
      - ./source/:/site
      - ./gems:/usr/local/bundle/

# setup
# docker-compose -f docker-compose.yml -f docker-compose-setup.yml up

# docker run -it --rm -v $(pwd)/source:/site bretfisher/jekyll new . --force
# docker run -it --rm --entrypoint bash -v $(pwd)/source:/site -v $(pwd)/gems:/usr/local/bundle/ bretfisher/jekyll bundle package